
import Sidebar from '../components/Sidebar'
import './globals.css'
import { SessionProvider } from '@/components/SessionProvider'
import {getServerSession} from 'next-auth'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import Login from '../components/Login'
import { authOptions } from '../../pages/api/auth/[...nextauth]'
import ClientProvider from '@/components/ClientProvider'
import LoginNavbar from '@/components/LoginNavbar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);
  console.log(session)
  return (
    <html lang="en" className='' >
      
      <body className={ `${inter.className} ` }>
        
       <SessionProvider session={session}>
        {/* if session is available means user has logged in  so show the component
        otherwise loginpage appears */}
        {!session?(
          <Login/>
        )
        :
        (
          
          <div className='flex '>
         {/* <div className='max-w-xs h-screen overflow-y-auto'>
          <Sidebar/>
        </div> */}
         <ClientProvider/>
         {/* //remvoed flex-1 from here */}
        <div className=' flex-1 dark:bg-[#191919] '>
       
          {children}
     
          </div>
          
        </div>
        
      )}
        </SessionProvider>
        </body>
       
    </html>
  )
}
